easy_admin:
    formats:
        date:     'd/m/Y'
        time:     'H:i'
        datetime: 'd/m/Y H:i:s'
    site_name: 'LPSA Admin'
    design:
        brand_color: '#7C97A1'
        menu:
            - label: MENU PRINCIPAL
            - { entity: 'Candidat', label: 'Candidats', params:{ action: 'list' }, icon: 'users' }
            - { entity: 'Rh', label: 'RH', params:{ action: 'list' }, icon: 'user' }
            - { entity: 'Cv', label: 'Liste CVs', params:{ action: 'list' }, icon: 'copy' }
            - label: CVs Options
              icon: copy
              children:
                    - { entity: 'Sport', label: 'Sport', params:{ action: 'list' } }
                    - { entity: 'Hobby', label: 'Hobbies', params:{ action: 'list' }}
                    - { entity: 'Nationality', label: 'Nationalité', params:{ action: 'list' }}
                    - { entity: 'UserStatut', label: 'Statuts', params:{ action: 'list' }}
            - { entity: 'Interview', label: 'Interviews', params:{ action: 'list' }, icon: 'microphone' }
            - { entity: 'Tag', label: 'Tags', params:{ action: 'list' }, icon: 'tag' }
    entities:
        Candidat:
            class: App\Entity\User
            label: 'Candidats'
            list:
                title: "Liste de candidats"
                max_results: 10
                dql_filter: "entity.roles LIKE '%%ROLE_CANDIDAT%%'"
                fields: [{ property: 'lastName', label: 'Nom' }, { property: 'firstName', label: 'Prénom' }, { property: 'phoneNumber', label: 'Numéro phone' }, { property: 'enabled', label: 'Activé/Désactivé' }, { property: 'roles', label: 'Rôles'}]
        
        Rh:
            class: App\Entity\User
            label: 'Rh'
            list:
                title: "Liste RH"
                max_results: 10
                dql_filter: "entity.roles LIKE '%%ROLE_RH%%'"
                fields: [{ property: 'lastName', label: 'Nom' }, { property: 'firstName', label: 'Prénom' }, { property: 'phoneNumber', label: 'Numéro phone' }, { property: 'enabled', label: 'Activé/Désactivé' }, { property: 'roles', label: 'Rôles'}]
            edit:
                fields: [{ property: 'lastName', label: 'Nom' }, { property: 'firstName', label: 'Prénom' }, { property: 'email', label: 'Email' }, { property: 'phoneNumber', label: 'Numéro phone' }, { property: 'maritalStatus', label: 'Situation Matrimoniale' }, { property: 'password', type: 'password', label: 'Mot de passe' }, { property: 'roles', label: 'Rôles'}]

        Cv:
            class: App\Entity\User
            label: 'Cv'
            list:
                title: "Liste de CVs"
                max_results: 10
                dql_filter: "entity.submit = 1 AND entity.roles LIKE '%%ROLE_CANDIDAT%%'"
                actions: ['-new', '-edit', '-show', '-delete', { name: 'show_cv', type: 'route', label: 'Voir détail Cv' }]
                fields: [{ property: 'profileName', type: 'image', label: 'Photo', base_path: '%app.path.profil%' }, { property: 'lastName', label: 'Nom' }, { property: 'firstName', label: 'Prénom' }, { property: 'email', label: 'Email' }, { property: 'phoneNumber', label: 'Numéro phone' }]

        Sport:
            class: App\Entity\Sport
            label: 'Sports disponible'
            list:
                fields: [{ property: 'name', label: 'Nom' }]

        Hobby:
            class: App\Entity\Hobby
            label: 'Hobbies'
            list:
                fields: [{property: 'name', label: 'Nom'}]

        Nationality:
            class: App\Entity\Nationality
            label: 'Nationalités'
            list:
                fields: [{property: 'nationality', label: 'Nationalité'}, {property: 'countryCode', label: 'Code Pays'}]

        Interview:
            class: App\Entity\Interview
            label: 'Interviews'
            list:
                fields: [{property: 'interviewBy', label: 'Interviewer'}, {property: 'user', label: 'Interviewee'}, {property: 'interviewResume', label: 'Résumé'}, {property: 'interviewDate', label: 'Date'}]

        Tag:
            class: App\Entity\Tag
            label: 'Les tags'
            list:
                fields: [{property: 'name', label: 'Tag'}]

        UserStatut:
            class: App\Entity\UserStatut
            label: 'Statuts'
            list:
                fields: [{property: 'statut', label: 'Statuts'}]
            form:
                fields: ['statut']

        User:
            class: App\Entity\User
            label: 'Candidats'
            list:
                title: "Liste des Utilisateurs"
                max_results: 10
                fields: [{ property: 'lastName', label: 'Nom' }, { property: 'firstName', label: 'Prénom' }, { property: 'phoneNumber', label: 'Numéro phone' }, { property: 'enabled', label: 'Activé/Désactivé' }, { property: 'roles', label: 'Rôles'}]