fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    service:                               
        mailer: fos_user.mailer.twig_swift
    from_email:
        address: "noreplay@passion4humanity.com"
        sender_name: "noreplay@passion4humanity.com"
    registration:
        form:
            type: App\Form\RegistrationType
    resetting:
        email:
            template:   emails/password_resetting.email.twig