nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['*']
    paths:
        '^/api/':
          allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
          allow_methods: ['POST', 'PUT', 'PATCH', 'GET', 'DELETE']
          allow_headers: ['Content-Type', 'Authorization']
          max_age: 3600
        '^/': ~
