vich_uploader:
    db_driver: orm

    mappings:
        profil:
            uri_prefix: /uploads/photos
            upload_destination: '%kernel.project_dir%/public/uploads/photos'
            namer: vich_uploader.namer_uniqid
